version: '3.9'

services:
  app_proxy:
    environment:
      APP_HOST: denny-grist_server_1
      APP_PORT: 8484
      PROXY_AUTH_ADD: "false"
  server:
    image: gristlabs/grist:1.6.1@sha256:d9d35c82799bfa2e0438bb60385fb0b550465dabde2a6e0ceca8afec1aae3305
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data:/persist
