version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denny-opencloud_web_1
      APP_PORT: 9200

  web:
    image: opencloudeu/opencloud-rolling:latest
    restart: on-failure
    environment:
      OC_INSECURE: "true"
      PROXY_HTTP_ADDR: "0.0.0.0:9200"
      OC_URL: "http://umbrel-2.local:9200"
    volumes:
      - opencloud-config:/etc/opencloud
      - opencloud-data:/var/lib/opencloud
    entrypoint: >
      /bin/sh -c '
        if [ ! -f /etc/opencloud/config.yml ]; then
          echo "jwt_secret: $(head -c 32 /dev/urandom | xxd -p)" > /etc/opencloud/config.yml;
          echo "Generated jwt_secret in config.yml";
        fi;
        exec docker-entrypoint.sh "$@"
      '

volumes:
  opencloud-config:
  opencloud-data:
