version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denny-opencloud_opencloud_1
      APP_PORT: 9200

  opencloud:
    image: ghcr.io/opencloud-eu/opencloud-rolling:latest
    container_name: denny-opencloud_opencloud_1
    restart: unless-stopped
    environment:
      INITIAL_ADMIN_USER: admin
      INITIAL_ADMIN_PASSWORD: "DEIN.SICHERES.PASSWORT"
      # Optional: Weitere Umgebungsvariablen aus der offiziellen .env
    volumes:
      - ${APP_DATA_DIR}/opencloud/data:/var/lib/opencloud
      - ${APP_DATA_DIR}/opencloud/config:/etc/opencloud
