version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denny-opencloud_app_1
      APP_PORT: 9200

  app:
    image: opencloudeu/opencloud-rolling:latest
    user: "0:0"
    restart: on-failure
    environment:
      - OC_INSECURE=true                # HTTPS deaktivieren → nur HTTP
      - PROXY_HTTP_ADDR=0.0.0.0:9200    # OpenCloud hört auf HTTP-Port 9200
      - OC_URL=http://umbrel-2.local:8844
    volumes:
      - ${APP_DATA_DIR}/config:/etc/opencloud
      - ${APP_DATA_DIR}/data:/var/lib/opencloud
