version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denny-opencloud_web_1
      APP_PORT: 9200

  web:
    image: opencloudeu/opencloud-rolling:latest
    restart: on-failure
    environment:
      OC_INSECURE: "true"
      PROXY_HTTP_ADDR: "0.0.0.0:9200"
      OC_URL: "http://umbrel-2.local:9200"
    volumes:
      - ${APP_DATA_DIR}/data/config:/etc/opencloud
      - ${APP_DATA_DIR}/data/data:/var/lib/opencloud
