version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denny-opencloud_web_1
      APP_PORT: 8080

  web:
    image: opencloudeu/opencloud-rolling:latest
    container_name: denny-opencloud_web_1
    user: "1000:1000"
    entrypoint: ["/bin/sh", "-c"]
    command: >
      if [ ! -f /opencloud/config/opencloud.yaml ]; then
        opencloud init --config /opencloud/config/opencloud.yaml;
      fi;
      opencloud server --config /opencloud/config/opencloud.yaml
    environment:
      OC_URL: https://umbrel.local:8844
      OC_LOG_LEVEL: info
      OC_LOG_COLOR: "false"
      OC_LOG_PRETTY: "false"
      OC_INSECURE: "true"
      IDM_ADMIN_PASSWORD: "admin123"
      PROXY_CSP_CONFIG_FILE_LOCATION: /opencloud/config/csp.yaml
    volumes:
      - ${APP_DATA_DIR}/config:/opencloud/config
      - ${APP_DATA_DIR}/data:/var/lib/opencloud
      - ${APP_DATA_DIR}/apps:/var/lib/opencloud/web/assets/apps
    restart: always
    networks:
      - opencloud-net
    logging:
      driver: local

networks:
  opencloud-net:
