version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denny-opencloud_web_1
      APP_PORT: 8080

  web:
    image: opencloudeu/opencloud-rolling:latest
    entrypoint:
      - /bin/sh
    command: ["-c", "opencloud init || true; opencloud server"]
    environment:
      OC_ADD_RUN_SERVICES: ""
      OC_URL: https://umbrel-2.local:8844
      OC_LOG_LEVEL: info
      OC_LOG_COLOR: "false"
      OC_LOG_PRETTY: "false"
      PROXY_TLS: "false"
      OC_INSECURE: "true"
      PROXY_ENABLE_BASIC_AUTH: "false"
      IDM_CREATE_DEMO_USERS: "false"
      IDM_ADMIN_PASSWORD: "admin123"
      NOTIFICATIONS_SMTP_HOST: ""
      NOTIFICATIONS_SMTP_PORT: ""
      NOTIFICATIONS_SMTP_SENDER: "OpenCloud notifications <notifications@umbrel.local>"
      NOTIFICATIONS_SMTP_USERNAME: ""
      NOTIFICATIONS_SMTP_PASSWORD: ""
      NOTIFICATIONS_SMTP_INSECURE: ""
      NOTIFICATIONS_SMTP_AUTHENTICATION: ""
      NOTIFICATIONS_SMTP_ENCRYPTION: "none"
      FRONTEND_ARCHIVER_MAX_SIZE: "10000000000"
      PROXY_CSP_CONFIG_FILE_LOCATION: /etc/opencloud/csp.yaml
      OC_PASSWORD_POLICY_BANNED_PASSWORDS_LIST: banned-password-list.txt
      OC_SHARING_PUBLIC_SHARE_MUST_HAVE_PASSWORD: "true"
      OC_SHARING_PUBLIC_WRITEABLE_SHARE_MUST_HAVE_PASSWORD: "true"
      OC_PASSWORD_POLICY_DISABLED: "false"
      OC_PASSWORD_POLICY_MIN_CHARACTERS: "8"
      OC_PASSWORD_POLICY_MIN_LOWERCASE_CHARACTERS: "1"
      OC_PASSWORD_POLICY_MIN_UPPERCASE_CHARACTERS: "1"
      OC_PASSWORD_POLICY_MIN_DIGITS: "1"
      OC_PASSWORD_POLICY_MIN_SPECIAL_CHARACTERS: "1"
    volumes:
      - ${APP_DATA_DIR}/config/csp.yaml:/etc/opencloud/csp.yaml
      - ${APP_DATA_DIR}/config/banned-password-list.txt:/etc/opencloud/banned-password-list.txt
      - ${APP_DATA_DIR}/config:/etc/opencloud
      - ${APP_DATA_DIR}/data:/var/lib/opencloud
      - ${APP_DATA_DIR}/apps:/var/lib/opencloud/web/assets/apps
    logging:
      driver: local
    restart: on-failure