version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denny-taxhacker_app_1
      APP_PORT: 7331

  app:
    image: ghcr.io/vas3k/taxhacker:latest
    environment:
      NODE_ENV: production
      SELF_HOSTED_MODE: "true"
      UPLOAD_PATH: /app/data/uploads
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/taxhacker
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
    restart: unless-stopped
    depends_on:
      - postgres
    logging:
      driver: "local"
      options:
        max-size: "100M"
        max-file: "3"

  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: taxhacker
    volumes:
      - ${APP_DATA_DIR}/pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    logging:
      driver: "local"
      options:
        max-size: "100M"
        max-file: "3"
