version: "3.7"

volumes:
  caddy_data:
  caddy_config:
  pwpush_db_data:

x-op-app-environment: &x-op-app-environment
  environment:
    # Datenbank-URL für Postgres im Docker Netzwerk (db Service)
    DATABASE_URL: 'postgres://pwpush_user:pwpush_passwd@db:5432/pwpush_db'

services:
  pwpush:
    image: docker.io/pglombardo/pwpush:latest
    restart: unless-stopped
    depends_on:
      - db
    <<: *x-op-app-environment

  worker:
    image: docker.io/pglombardo/pwpush-worker:latest
    restart: unless-stopped
    depends_on:
      - pwpush
      - db
    <<: *x-op-app-environment

  ssl_proxy:
    image: caddy:latest
    restart: unless-stopped
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - pwpush

  db:
    image: docker.io/postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: pwpush_user
      POSTGRES_PASSWORD: pwpush_passwd
      POSTGRES_DB: pwpush_db
    volumes:
      - pwpush_db_data:/var/lib/postgresql/data

  app_proxy:
    environment:
      APP_HOST: denny-pwpush_web_1
      APP_PORT: 5100
