version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: denny-mstream_server_1
      APP_PORT: 3000

  server:
    image: lscr.io/linuxserver/mstream:latest
    restart: on-failure
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APP_DATA_DIR}/data:/config
      - ${APP_DATA_DIR}/music:/music