version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denny-odoo_web_1
      APP_PORT: 8069

  web:
    image: odoo:17.0
    depends_on:
      - db
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ${APP_DATA_DIR}/data/config:/etc/odoo
      - ${APP_DATA_DIR}/data/addons:/mnt/extra-addons

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=myodoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata

volumes:
  odoo-web-data:
  odoo-db-data:
