version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denny-peppermint_web_1
      APP_PORT: 3000

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: peppermint
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: peppermint

  web:
    image: pepperlabs/peppermint:latest
    restart: unless-stopped
    depends_on:
      - db
    environment:
      DB_USERNAME: "peppermint"
      DB_PASSWORD: "1234"
      DB_HOST: "db"
      SECRET: 'peppermint4life'