version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denny-olivetin_app_1
      APP_PORT: 1337

  app:
    image: jamesread/olivetin
    volumes:
      - ${APP_DATA_DIR}/config:/config 
    restart: unless-stopped


volumes:
  OliveTin-config:
    external: false