version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denny-browserless_web_1
      APP_PORT: 3000

  web:
    image: ghcr.io/browserless/base:v2.33.0
    restart: on-failure
    environment:
      - MAX_CONCURRENT_SESSIONS=10
      - ENABLE_DEBUGGER=true
    volumes:
      - ${APP_DATA_DIR}/data:/data

