version: "3.7"

services:
  app:
    image: ghcr.io/browserless/chromium:latest
    restart: always
    ports:
      - "3353:3000"
    environment:
      - MAX_CONCURRENT_SESSIONS=10
      - ENABLE_DEBUGGER=true
    volumes:
      - ${APP_DATA_DIR}/data:/data
