version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: denny-wger_web_1
      APP_PORT: 8000

  web:
    image: wger/wger:latest
    restart: unless-stopped
    depends_on:
      - db
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: wger
      POSTGRES_USER: wger
      POSTGRES_PASSWORD: wger
      DJANGO_SETTINGS_MODULE: wger.settings.live
      UWSGI_STATIC_MAP: /static=/home/wger/static
      UWSGI_MEDIA_MAP: /media=/home/wger/media
    volumes:
      - static:${APP_DATA_DIR}/static
      - media:${APP_DATA_DIR}/media
    command: >
      bash -c "
        python3 manage.py migrate &&
        python3 manage.py collectstatic --noinput &&
        gunicorn wsgi:application -b 0.0.0.0:8000
      "

  db:
    image: postgres:13
    restart: unless-stopped
    environment:
      POSTGRES_DB: wger
      POSTGRES_USER: wger
      POSTGRES_PASSWORD: wger
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
  static:
  media:
