version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: denny-wger_nginx_1
      APP_PORT: 80

  web:
    image: wger/server:latest
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy
    env_file:
      - ${APP_DATA_DIR}/config/prod.env
    volumes:
      - ${APP_DATA_DIR}/static:/home/wger/static
      - ${APP_DATA_DIR}/media:/home/wger/media
    expose:
      - 8000
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8000
      interval: 10s
      timeout: 5s
      start_period: 300s
      retries: 5
    restart: unless-stopped

  nginx:
    image: nginx:stable
    depends_on:
      - web
    volumes:
      - ${APP_DATA_DIR}/config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ${APP_DATA_DIR}/static:/wger/static:ro
      - ${APP_DATA_DIR}/media:/wger/media:ro
    expose:
      - 80
    healthcheck:
      test: service nginx status
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=wger
      - POSTGRES_PASSWORD=wger
      - POSTGRES_DB=wger
      - TZ=Europe/Berlin
    volumes:
      - ${APP_DATA_DIR}/postgres-data:/var/lib/postgresql/data/
    expose:
      - 5432
    healthcheck:
      test: pg_isready -U wger
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  cache:
    image: redis
    expose:
      - 6379
    volumes:
      - ${APP_DATA_DIR}/redis-data:/data
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  celery_worker:
    image: wger/server:latest
    command: /start-worker
    env_file:
      - ${APP_DATA_DIR}/config/prod.env
    volumes:
      - ${APP_DATA_DIR}/media:/home/wger/media
    depends_on:
      web:
        condition: service_healthy
    healthcheck:
      test: celery -A wger inspect ping
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  celery_beat:
    image: wger/server:latest
    command: /start-beat
    volumes:
      - ${APP_DATA_DIR}/celery-beat:${APP_DATA_DIR}/beat/
    env_file:
      - ${APP_DATA_DIR}/config/prod.env
    depends_on:
      celery_worker:
        condition: service_healthy
