version: "3.7"

x-backend: &common
  image: papermerge/papermerge:3.5.3@sha256:78c7a24609066b253cad18c6f8486af505e3b8da30aa73a45f064359a6516d16
  environment:
    PAPERMERGE__SECURITY__SECRET_KEY: moneyprintergobrrr123
    PAPERMERGE__AUTH__USERNAME: admin
    PAPERMERGE__AUTH__PASSWORD: umbrel
    PAPERMERGE__DATABASE__URL: postgresql://papermergeuser:papermergepass@db:5432/papermerge
    PAPERMERGE__REDIS__URL: redis://redis:6379/0
  volumes:
    - ${APP_DATA_DIR}/data/core:/core_app/index_db:rw
    - ${APP_DATA_DIR}/data/media:/core_app/media:rw

services:
  app_proxy:
    environment:
      APP_HOST: denny-papermerge_web_1
      APP_PORT: 80

  web:
    <<: *common
    container_name: Papermerge-WEB
    ports:
      - 12000:80
    depends_on:
      - redis
      - db

  worker:
    <<: *common
    command: worker
    container_name: Papermerge-WORKER
    depends_on:
      - redis
      - db

  redis:
    image: redis:7
    container_name: Papermerge-REDIS
    security_opt:
      - no-new-privileges:true
    volumes:
      - ${APP_DATA_DIR}/data/redis:/data:rw

  db:
    image: bitnami/postgresql:16.1.0@sha256:087f154f6c6ac96694e8a1858fbab4fb962fb8703277fa1b61e05f2871e1ba68
    container_name: Papermerge-DB
    environment:
      POSTGRESQL_USER: papermergeuser
      POSTGRESQL_PASSWORD: papermergepass
      POSTGRESQL_POSTGRES_PASSWORD: papermergepass
      POSTGRESQL_DATABASE: papermerge
    volumes:
      - ${APP_DATA_DIR}/data/db:/bitnami/postgresql:rw
