[app]
address = "0.0.0.0:9000"
admin_username = "admin"
admin_password = "umbrel"

[db]
host = "db"
port = 5432
user = "listmonk"
password = "listmonk"
database = "listmonk"
ssl_mode = "disable"

[uploads]
dir = "./uploads"
