version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denny-kuvasz_web_1
      APP_PORT: 8080

  web:
    image: kuvaszmonitoring/kuvasz:2.1.0@sha256:1e17da63d7bce59048cbf8bd46caa4c7c6f73a04becda065f5a140e070b1d474
    restart: on-failure
    environment:
      DATABASE_HOST: db
      DATABASE_USER: kuvaszuser
      DATABASE_PASSWORD: kuvaszpass
      ADMIN_USER: admin
      ADMIN_PASSWORD: umbrel
      ADMIN_API_KEY: dOxZYTTZgXKMHkqLBIQVImayQXAVWdzGBPuFJKggzcgvgPJPXpWzqzKaUOIOGGIr
    volumes:
      - ${APP_DATA_DIR}/data/config/kuvasz.yml:/config/kuvasz.yml
    depends_on:
      - db

  db:
    image: postgres:17.5@sha256:3962158596daaef3682838cc8eb0e719ad1ce520f88e34596ce8d5de1b6330a1
    restart: on-failure
    environment:
      POSTGRES_DB: kuvasz
      POSTGRES_USER: kuvaszuser
      POSTGRES_PASSWORD: kuvaszpass
    volumes:
      - ${APP_DATA_DIR}/data/db:/var/lib/postgresql/data:rw