version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: denny-librephotos_proxy_1
      APP_PORT: 80

  proxy:
    image: reallibrephotos/librephotos-proxy:latest
    container_name: denny-librephotos_proxy_1
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/scan:/data
      - ${APP_DATA_DIR}/data/protected_media:/protected_media
    expose:
      - "80"
    depends_on:
      - backend
      - frontend

  db:
    image: pgautoupgrade/pgautoupgrade:latest
    container_name: denny-librephotos_db_1
    restart: on-failure
    environment:
      POSTGRES_USER: librephotos
      POSTGRES_PASSWORD: librephotos
      POSTGRES_DB: librephotos
    volumes:
      - ${APP_DATA_DIR}/data/db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "psql", "-U", "librephotos", "-d", "librephotos", "-c", "SELECT 1;"]
      interval: 5s
      timeout: 5s
      retries: 5

  frontend:
    image: reallibrephotos/librephotos-frontend:latest
    container_name: denny-librephotos_frontend_1
    restart: on-failure

  backend:
    image: reallibrephotos/librephotos:latest
    container_name: denny-librephotos_backend_1
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/scan:/data
      - ${APP_DATA_DIR}/data/protected_media:/protected_media
      - ${APP_DATA_DIR}/data/logs:/logs
      - ${APP_DATA_DIR}/data/cache:/root/.cache
    environment:
      SECRET_KEY: changeme123
      BACKEND_HOST: backend
      ADMIN_EMAIL: admin@example.com
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: password
      DB_BACKEND: postgresql
      DB_NAME: librephotos
      DB_USER: librephotos
      DB_PASS: librephotos
      DB_HOST: db
      DB_PORT: 5432
      MAPBOX_API_KEY: ""
      WEB_CONCURRENCY: 1
      SKIP_PATTERNS: ""
      ALLOW_UPLOAD: "false"
      CSRF_TRUSTED_ORIGINS: ""
      DEBUG: "0"
    depends_on:
      db:
        condition: service_healthy

