version: "3.7"

services:

  app_proxy:
    environment:
      APP_HOST: denny-dawarich_app_1
      APP_PORT: 3000

  db:
    image: postgis/postgis:17-3.5-alpine
    container_name: dawarich_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d dawarich"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - ${APP_DATA_DIR}/data/db:/var/lib/postgresql/data:rw
      - ${APP_DATA_DIR}/data/shared:/var/shared:rw
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dawarich_development
    shm_size: 1G
    restart: on-failure
    user: "1000:1000"

  redis:
    image: redis:7.4-alpine
    container_name: dawarich_redis
    command: redis-server
    user: "1000:1000"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping || exit 1"]
    volumes:
      - ${APP_DATA_DIR}/data/redis:/data:rw
    environment:
      TZ: Europe/Berlin
    restart: on-failure

  app:
    image: freikin/dawarich:latest
    container_name: dawarich_app
    volumes:
      - ${APP_DATA_DIR}/data/public:/var/app/public:rw
      - ${APP_DATA_DIR}/data/watched:/var/app/tmp/imports/watched:rw
      - ${APP_DATA_DIR}/data/storage:/var/app/storage:rw
    stdin_open: true
    tty: true
    entrypoint: web-entrypoint.sh
    command: ['bin/rails', 'server', '-p', '3000', '-b', '::']
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://dawarich_redis:6379
      DATABASE_HOST: dawarich_db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: dawarich_development
      SELF_HOSTED: true
      STORE_GEODATA: true
      SECRET_KEY_BASE: dOxZYTTZgXKMHkqLBIQVImayQXAVWdzGBPuFJKggzcgvgPJPXpWzqzKaUOIOGGIr
      APPLICATION_HOSTS: umbrel-2.local:8955
      MIN_MINUTES_SPENT_IN_CITY: 60
      TIME_ZONE: Europe/Berlin
      APPLICATION_PROTOCOL: http
      DISTANCE_UNIT: km
      PROMETHEUS_EXPORTER_ENABLED: false
      PROMETHEUS_EXPORTER_HOST: 0.0.0.0
      PROMETHEUS_EXPORTER_PORT: 9394
      ENABLE_TELEMETRY: false
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO - http://127.0.0.1:3000/api/v1/health | grep -q '\"status\"\\s*:\\s*\"ok\"'"]
      interval: 10s
      retries: 30
      start_period: 30s
      timeout: 10s
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: on-failure
    user: "1000:1000"

  sidekiq:
    image: freikin/dawarich:latest
    container_name: dawarich_sidekiq
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f sidekiq"]
      interval: 10s
      retries: 30
      start_period: 30s
      timeout: 10s
    volumes:
      - ${APP_DATA_DIR}/data/public:/var/app/public:rw
      - ${APP_DATA_DIR}/data/watched:/var/app/tmp/imports/watched:rw
      - ${APP_DATA_DIR}/data/storage:/var/app/storage:rw
    stdin_open: true
    tty: true
    entrypoint: sidekiq-entrypoint.sh
    command: ['sidekiq']
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://dawarich_redis:6379
      DATABASE_HOST: dawarich_db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: dawarich_development
      SECRET_KEY_BASE: dOxZYTTZgXKMHkqLBIQVImayQXAVWdzGBPuFJKggzcgvgPJPXpWzqzKaUOIOGGIr
      APPLICATION_HOSTS: umbrel-2.local:8955
      BACKGROUND_PROCESSING_CONCURRENCY: 10
      APPLICATION_PROTOCOL: http
      PROMETHEUS_EXPORTER_ENABLED: false
      PROMETHEUS_EXPORTER_HOST: dawarich_app
      PROMETHEUS_EXPORTER_PORT: 9394
      SELF_HOSTED: true
      STORE_GEODATA: true
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      app:
        condition: service_healthy
    restart: on-failure
    user: "1000:1000"
