services:

  app_proxy:
    environment:
      APP_HOST: denny-dawarich_app_1
      APP_PORT: 3000

  db:
    image: postgis/postgis:17-3.5-alpine
    volumes:
      - ${APP_DATA_DIR}/data/db:/var/lib/postgresql/data:rw
      - ${APP_DATA_DIR}/data/shared:/var/shared:rw
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dawarich_development
    shm_size: 1G
    restart: on-failure

  redis:
    image: redis:7.4-alpine
    command: redis-server
    user: "1000:1000"
    volumes:
      - ${APP_DATA_DIR}/data/redis:/data:rw
    environment:
      TZ: Europe/Berlin
    restart: on-failure

  app:
    image: freikin/dawarich:latest
    volumes:
      - ${APP_DATA_DIR}/data/public:/var/app/public:rw
      - ${APP_DATA_DIR}/data/watched:/var/app/tmp/imports/watched:rw
      - ${APP_DATA_DIR}/data/storage:/var/app/storage:rw
    stdin_open: true
    tty: true
    entrypoint: web-entrypoint.sh
    command: ['bin/rails', 'server', '-p', '3000', '-b', '::']
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://redis:6379
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: dawarich_development
      SELF_HOSTED: true
      STORE_GEODATA: true
      SECRET_KEY_BASE: dOxZYTTZgXKMHkqLBIQVImayQXAVWdzGBPuFJKggzcgvgPJPXpWzqzKaUOIOGGIr
      APPLICATION_HOSTS: umbrel-2.local:8955
      MIN_MINUTES_SPENT_IN_CITY: 60
      TIME_ZONE: Europe/Berlin
      APPLICATION_PROTOCOL: http
      DISTANCE_UNIT: km
      PROMETHEUS_EXPORTER_ENABLED: false
      PROMETHEUS_EXPORTER_HOST: 0.0.0.0
      PROMETHEUS_EXPORTER_PORT: 9394
      ENABLE_TELEMETRY: false
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    depends_on:
      - db
      - redis
    restart: on-failure
    user: "1000:1000"

  sidekiq:
    image: freikin/dawarich:latest
    volumes:
      - ${APP_DATA_DIR}/data/public:/var/app/public:rw
      - ${APP_DATA_DIR}/data/watched:/var/app/tmp/imports/watched:rw
      - ${APP_DATA_DIR}/data/storage:/var/app/storage:rw
    stdin_open: true
    tty: true
    entrypoint: sidekiq-entrypoint.sh
    command: ['sidekiq']
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://redis:6379
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: dawarich_development
      SECRET_KEY_BASE: dOxZYTTZgXKMHkqLBIQVImayQXAVWdzGBPuFJKggzcgvgPJPXpWzqzKaUOIOGGIr
      APPLICATION_HOSTS: umbrel-2.local:8955
      BACKGROUND_PROCESSING_CONCURRENCY: 10
      APPLICATION_PROTOCOL: http
      PROMETHEUS_EXPORTER_ENABLED: false
      PROMETHEUS_EXPORTER_HOST: dawarich_app
      PROMETHEUS_EXPORTER_PORT: 9394
      SELF_HOSTED: true
      STORE_GEODATA: true
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    depends_on:
      - db
      - redis
      - app
    restart: on-failure
    user: "1000:1000"
