version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: denny-cryptgeon_app_1
      APP_PORT: 8000

  redis:
    image: redis:7-alpine
    command: >
      redis-server
      --save ""
      --appendonly no
      --maxmemory 1gb
      --maxmemory-policy allkeys-lru
    tmpfs:
      - /data

  app:
    image: cupcakearmy/cryptgeon:latest
    depends_on:
      - redis
    environment:
      SIZE_LIMIT: 4 MiB
    restart: on-failure
