version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denny-sincin_web_1
      APP_PORT: 8080

  web:
    image: syncin/server:latest
    restart: on-failure
    working_dir: /app
    user: "8888:8888"
    environment:
      - INIT_ADMIN_PASSWORD
      - INIT_ADMIN_LOGIN
    volumes:
      - ${APP_DATA_DIR}/environment.yaml:/app/environment/environment.yaml
      - ${APP_DATA_DIR}/data:/app/data
      - ${APP_DATA_DIR}/desktop_releases:/app/static/releases:ro
    depends_on:
      - db
    logging:
      driver: json-file
      options:
        max-size: "25m"
        max-file: "5"

  db:
    image: mariadb:11
    restart: on-failure
    command: --innodb_ft_cache_size=16000000 --max-allowed-packet=1G
    environment:
      MYSQL_ROOT_PASSWORD: MySQLRootPassword
      MYSQL_DATABASE: sync_in
    volumes:
      - ${APP_DATA_DIR}/mariadb:/var/lib/mysql
