services:
  app_proxy:
    environment:
      APP_HOST: denny-materialious_app_1
      APP_PORT: 80

  app:
    image: wardpearce/materialious:1.10.3@sha256:58be2695e92207388d407944de5cb911c4f99ce6de7f1e755f2687722ef30b34
    restart: on-failure
    environment:
      VITE_DEFAULT_INVIDIOUS_INSTANCE: "http://192.168.178.101:3420"
      VITE_DEFAULT_RETURNYTDISLIKES_INSTANCE: "https://returnyoutubedislikeapi.com"
      VITE_DEFAULT_SPONSERBLOCK_INSTANCE: "https://sponsor.ajay.app"
      VITE_DEFAULT_DEARROW_INSTANCE: "https://sponsor.ajay.app"
      VITE_DEFAULT_DEARROW_THUMBNAIL_INSTANCE: "https://dearrow-thumb.ajay.app"
    volumes:
      - ${APP_DATA_DIR}/data:/data
