version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denny-tubearchivist_app_1
      APP_PORT: 8000

  app:
    image: bbilly1/tubearchivist:latest
    environment:
      - ES_URL=http://tubearchivist-es:9200
      - TA_USERNAME=admin
      - TA_PASSWORD=umbrel
      - TA_HOST=http://${DEVICE_DOMAIN_NAME}:8686
      - REDIS_CON=redis://redis:6379
      - ELASTIC_PASSWORD=tubearchivistpass
    volumes:
      - ${APP_DATA_DIR}/data/media:/youtube:rw
      - ${APP_DATA_DIR}/data/cache:/cache:rw
    restart: on-failure
    depends_on:
      - es
      - redis
      
  es:
    image: elastic/elasticsearch:8.14.3
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment:
      - ELASTIC_PASSWORD=tubearchivistpass
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=true
      - discovery.type=single-node
      - path.repo=/usr/share/elasticsearch/data/snapshot
    volumes:
      - ${APP_DATA_DIR}/data/es:/usr/share/elasticsearch/data:rw
    restart: on-failure

  redis:
    image: redis:7
    volumes:
      - ${APP_DATA_DIR}/data/redis:/data:rw
    restart: on-failure
    depends_on:
      - es
