version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denny-tubearchivist_app_1
      APP_PORT: 8000

  app:
    image: bbilly1/tubearchivist
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/tubearchivist/media:/youtube
      - ${APP_DATA_DIR}/tubearchivist/cache:/cache
    environment:
      - ES_URL=http://archivist-es:9200
      - REDIS_CON=redis://archivist-redis:6379
      - HOST_UID=1000
      - HOST_GID=1000
      - TA_HOST=http://tubearchivist.local:8000
      - TA_USERNAME=tubearchivist
      - TA_PASSWORD=verysecret
      - ELASTIC_PASSWORD=verysecret
      - TZ=Europe/Berlin
    depends_on:
      - es
      - redis

  redis:
    image: redis:7
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/tubearchivist/redis:/data
    depends_on:
      - es

  es:
    image: bbilly1/tubearchivist-es
    restart: on-failure
    environment:
      - ELASTIC_PASSWORD=verysecret
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=true
      - discovery.type=single-node
      - path.repo=/usr/share/elasticsearch/data/snapshot
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ${APP_DATA_DIR}/tubearchivist/es:/usr/share/elasticsearch/data
