version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denny-slink_app_1
      APP_PORT: 3000

  app:
    image: anirdev/slink:v1.6.0@sha256:6823434c2bdfbac46bf3989767c58b8c0db8060ef7721cd8baaf154540c59a79
    user: "1000:1000"
    restart: on-failure
    environment:
      - TZ=UTC
      - ORIGIN=http://${DEVICE_DOMAIN_NAME}:8832
      - USER_APPROVAL_REQUIRED=false
      - STORAGE_PROVIDER=local
    volumes:
      - ${APP_DATA_DIR}/data/slink_data:/app/var/data:rw
      - ${APP_DATA_DIR}/data/images:/app/slink/images:rw
    command: >
      sh -c "
        sleep 5 &&
        slink user:activate --email=admin@admin.com &&
        slink user:grant:role --email=admin@admin.com ROLE_ADMIN &&
        slink serve
      "
