version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denny-slink_app_1
      APP_PORT: 3000

  app:
    image: anirdev/slink:v1.6.0@sha256:6823434c2bdfbac46bf3989767c58b8c0db8060ef7721cd8baaf154540c59a79
    restart: on-failure
    environment:
      - TZ=UTC
      - ORIGIN=http://${DEVICE_DOMAIN_NAME}:8832
      - USER_APPROVAL_REQUIRED=true
      - USER_PASSWORD_MIN_LENGTH=8
      - USER_PASSWORD_REQUIREMENTS=15
      - IMAGE_MAX_SIZE=15M
      - IMAGE_STRIP_EXIF_METADATA=true
      - IMAGE_COMPRESSION_QUALITY=80
      - STORAGE_PROVIDER=local
    volumes:
      - ${APP_DATA_DIR}/data/slink_data:/app/var/data
      - ${APP_DATA_DIR}/data/images:/app/slink/images
