version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: denny-btctracker_web_1
      APP_PORT: 3000

  web:
    image: dennysubke/btc-tracker:v0.6.0@sha256:aa55f48202236bf10a94907daa56ac37c95c367c54f12a2e87ba65bd306bee49
    user: 1000:1000
    environment:
      - NODE_ENV=development
      - PORT=3000
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data:/app/src/data


