services:
  app_proxy:
    environment:
      APP_HOST: denny-reitti_app_1
      APP_PORT: 8080
      
  app:
    image: dedicatedcode/reitti:latest
    restart: on-failure
    depends_on:
      - rabbitmq
      - postgis
      - redis
    environment:
      PHOTON_BASE_URL: http://photon:2322
    volumes:
      - ${APP_DATA_DIR}/data:/app/data

  postgis:
    image: postgis/postgis:17-3.5-alpine
    restart: on-failure
    environment:
      POSTGRES_USER: reitti
      POSTGRES_PASSWORD: reitti
      POSTGRES_DB: reittidb
    volumes:
      - ${APP_DATA_DIR}/postgis:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: on-failure
    environment:
      RABBITMQ_DEFAULT_USER: reitti
      RABBITMQ_DEFAULT_PASS: reitti
    volumes:
      - ${APP_DATA_DIR}/rabbitmq:/var/lib/rabbitmq

  redis:
    image: redis:7-alpine
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/redis:/data

  photon:
    image: rtuszik/photon-docker:latest
    restart: on-failure
    environment:
      UPDATE_STRATEGY: PARALLEL
      COUNTRY_CODE: de
    volumes:
      - ${APP_DATA_DIR}/photon:/photon/photon_data
