version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denny-mastodon_web_1
      APP_PORT: 80

  redis:
    image: redis
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping || exit 1"]
    user: 999:10
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ${APP_DATA_DIR}/data/redis:/data:rw
    restart: on-failure

  db:
    image: postgres:17
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "mastodon", "-U", "mastodonuser"]
      timeout: 45s
      interval: 10s
      retries: 10
    volumes:
      - ${APP_DATA_DIR}/data/db:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_DB: mastodon
      POSTGRES_USER: mastodonuser
      POSTGRES_PASSWORD: mastodonpw
    restart: on-failure
    
  mastodon:
    image: lscr.io/linuxserver/mastodon:latest
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=999
      - PGID=10
      - TZ=Europe/Berlin
      - DEFAULT_LOCALE=en
      - LOCAL_DOMAIN=umbrel-2.local:8836
      - WEB_DOMAIN=umbrel-2.local:8836
      - REDIS_HOST=mastodon-redis
      - REDIS_PORT=6379
      - DB_HOST=mastodon-db
      - DB_USER=mastodonuser
      - DB_NAME=mastodon
      - DB_PASS=mastodonpw
      - DB_PORT=5432
      - ES_ENABLED=false
      - ES_HOST=es
      - ES_PORT=9200
      - ES_USER=elastic
      - ES_PASS=elastic
      - SECRET_KEY_BASE=PIWLVVi14fqae5Ds8JqEGb3jGv3zVWJOoyxo6B2346vA00S3lzSL0cf3J0yxcB5pmu05qUHLQwIG8m8M97w56qvflufm7qdlRWoZoQ7sQjMDypdhRC54FcGD3rlSsBk4
      - OTP_SECRET=wjZtoiw3udx1V586bVkGCkg1MrZ0UuRBSKVj8ghsrF4eGSCPLMhHw234lGRwkTAMUKy5TRZbUXgPqK5POkvCVof8lse7KJGVPgWHdkwrvyzhUTPp8b1vvBMABVQ76rCM
      - ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY=6egLIdkH0vE5UXIwyZeU1qSL6tXwhd4j
      - ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY=bMQ59AJmJRCogwsgeFuqt8BXqwAf1Yt8
      - ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT=ZpawFWM4ArOqRZbRtkYXeIqIKWLlsYZX
      - S3_ENABLED=false
    volumes:
      - ${APP_DATA_DIR}/data/mastodon/config:/config:rw
    restart: on-failure
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_started