version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denny-rever_web_1
      APP_PORT: 3000
      
  api:
    image: reverfin/rever-api:latest
    restart: on-failure
    depends_on:
      - db
      - redis
      - minio
    environment:
      DB_NAME: reverdb
      DB_USER: reveruser
      DB_PASSWORD: reverpass
      DB_HOST: db
      REDIS_HOST: redis
      MINIO_ENDPOINT: minio
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: gunicorn rever.wsgi:application --bind 0.0.0.0:8000 -w 4 --max-requests 1200 --max-requests-jitter 1000 --access-logfile -

  web:
    image: reverfin/rever-frontend:latest
    restart: on-failure
    depends_on:
      - api
    environment:
      API_URL: http://api:8000

  worker:
    image: reverfin/rever-api:latest
    restart: on-failure
    depends_on:
      - db
      - redis
      - minio
    environment:
      DB_NAME: reverdb
      DB_USER: reveruser
      DB_PASSWORD: reverpass
      DB_HOST: db
      REDIS_HOST: redis
      MINIO_ENDPOINT: minio
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: celery -A rever worker --loglevel=info

  db:
    image: postgres:16-alpine
    restart: on-failure
    command: postgres -c 'max_connections=1000'
    volumes:
      - ${APP_DATA_DIR}/data/pgdata:/var/lib/postgresql/data
    environment:
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: reverdb
      POSTGRES_USER: reveruser
      POSTGRES_PASSWORD: reverpass

  redis:
    image: valkey/valkey:8.1.1-alpine
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/redisdata:/data
    command: ["--protected-mode", "no"]

  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    restart: on-failure
    command: sh -c 'mkdir -p /export/uploads && /usr/bin/minio server /export --console-address ":9090"'
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    volumes:
      - ${APP_DATA_DIR}/data/uploads:/export

  proxy:
    image: reverfin/rever-proxy:latest
    environment:
      NGINX_PORT: 80
      BUCKET_NAME: uploads
      FILE_SIZE_LIMIT: 5242880
    depends_on:
      - web
      - api
    restart: on-failure
