version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denny-freecad_app_1
      APP_PORT: 3000

  freecad:
    image: ghcr.io/linuxserver/freecad:latest
    restart: on-failure
    healthcheck:
      test: timeout 10s bash -c ':> /dev/tcp/127.0.0.1/3000' || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    security_opt:
      - no-new-privileges:true
      - seccomp:unconfined
    volumes:
      - ${APP_DATA_DIR}/freecad:/config:rw
    environment:
      - CUSTOM_USER=admin
      - PASSWORD=umbrel
      - TZ=Europe/Berlin
      - PUID=1000
      - PGID=1000
