version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denny-moncycle_app_1
      APP_PORT: 80

  app:
    image: jeanio/moncycle.app
    container_name: moncycle_app
    hostname: moncycle-app
    restart: unless-stopped
    environment:
      TZ: 'Europe/Paris'
      DB_HOST: db
      DB_ID: umbrel
      DB_NAME: moncycle
      DB_PORT: 3306
      DB_PASSWORD: your_db_password
      PHP_CACHE: 1
      PHP_SHOW_ERR: 0
      PHP_SECURE_COOKIES: 1
      CREATION_COMPTE: true
      CONNEXION_COMPTE: true
    volumes:
      - ${APP_DATA_DIR}/data:/var/www/html

  db:
    image: mariadb:10.11
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: your_db_password
      MARIADB_DATABASE: moncycle
      MARIADB_USER: umbrel
      MARIADB_PASSWORD: your_db_password
    volumes:
      - ${APP_DATA_DIR}/db:/var/lib/mysql
