version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denny-joplin_server_1
      APP_PORT: 22300

  db:
    image: postgres:16
    restart: on-failure
    user: "1000:1000"
    volumes:
      - ${APP_DATA_DIR}/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=joplinpass
      - POSTGRES_USER=joplinuser
      - POSTGRES_DB=joplindb

  server:
    image: joplin/server:latest
    restart: on-failure
    container_name: denny-joplin_server_1
    depends_on:
      - db
      - transcribe
    environment:
      - APP_PORT=22300
      - APP_BASE_URL=http://${DEVICE_DOMAIN_NAME}:22300
      - DB_CLIENT=pg
      - POSTGRES_PASSWORD=joplinpass
      - POSTGRES_DATABASE=joplindb
      - POSTGRES_USER=joplinuser
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=db
      - TRANSCRIBE_API_KEY=transcribekey123
      - TRANSCRIBE_BASE_URL=http://transcribe:4567
      - TRANSCRIBE_ENABLED=true
    volumes:
      - ${APP_DATA_DIR}/data:/var/lib/joplin

  transcribe-db:
    image: postgres:16
    restart: on-failure
    user: "1000:1000"
    volumes:
      - ${APP_DATA_DIR}/transcribe-postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=transcribepass
      - POSTGRES_USER=transcribeuser
      - POSTGRES_DB=transcribedb

  transcribe:
    image: joplin/transcribe:latest
    restart: on-failure
    depends_on:
      - transcribe-db
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${APP_DATA_DIR}/images:/app/packages/transcribe/images
    environment:
      - APP_PORT=4567
      - DB_CLIENT=pg
      - QUEUE_DATABASE_NAME=transcribedb
      - QUEUE_DATABASE_USER=transcribeuser
      - QUEUE_DATABASE_PASSWORD=transcribepass
      - QUEUE_DATABASE_PORT=5432
      - QUEUE_DATABASE_HOST=transcribe-db
      - API_KEY=transcribekey123
      - HTR_CLI_IMAGES_FOLDER=/app/packages/transcribe/images
