version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denny-rocketchat_app_1
      APP_PORT: 3000

  db:
    image: docker.io/bitnami/mongodb:7.0.5-debian-11-r22
    environment:
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_NAME: rs0
      ALLOW_EMPTY_PASSWORD: 1
      MONGODB_SYSTEM_LOG_VERBOSITY: 3
    volumes:
      - ${APP_DATA_DIR}/db:/bitnami/mongodb
    restart: on-failure

  app:
    image: rocketchat/rocket.chat:latest
    environment:
      MONGO_URL: mongodb://db:27017/rocketchat?replicaSet=rs0
      MONGO_OPLOG_URL: mongodb://db:27017/local?replicaSet=rs0
      ROOT_URL: http://umbrel-2.local:3458
      URL: http://umbrel-2.local:3458
      PORT: 3000
      DEPLOY_METHOD: docker
    volumes:
      - ${APP_DATA_DIR}/data:/app/uploads
    restart: on-failure
    depends_on:
      db:
