version: "3.7"

services:
  app_proxy:
    image: ghcr.io/umbrel/umbrel-app-proxy:latest
    container_name: denny-rocketchat_app_proxy_1
    environment:
      APP_HOST: rocketchat
      APP_PORT: 3000
    ports:
      - "3459:3459"
    depends_on:
      rocketchat:
        condition: service_healthy
    restart: unless-stopped

  mongo:
    image: mongo:7.0
    container_name: denny-rocketchat_mongo_1
    restart: on-failure:5
    volumes:
      - ${APP_DATA_DIR}/db:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    user: "1000:1000"

  rocketchat:
    image: rocketchat/rocket.chat:latest
    container_name: denny-rocketchat_rocketchat_1
    restart: on-failure:5
    environment:
      MONGO_URL: mongodb://mongo:27017/rocketchat
      ROOT_URL: http://umbrel-2.local:3459
      PORT: 3000
    volumes:
      - ${APP_DATA_DIR}/data:/app/uploads
    depends_on:
      mongo:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
