version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denny-rocketchat_app_1
      APP_PORT: 3000

  db:
    image: mongo:7
    restart: unless-stopped
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    volumes:
      - ${APP_DATA_DIR}/db:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  app:
    image: rocketchat/rocket.chat:latest
    environment:
      MONGO_URL: mongodb://db:27017/rocketchat?replicaSet=rs0
      MONGO_OPLOG_URL: mongodb://db:27017/local?replicaSet=rs0
      ROOT_URL: http://umbrel-2.local:3458
      PORT: 3000
      DEPLOY_METHOD: docker
    volumes:
      - ${APP_DATA_DIR}/data:/app/uploads
    restart: unless-stopped
    depends_on:
      - db
