version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denny-rocketchat_rocketchat_1
      APP_PORT: 3000

  mongo:
    container_name: denny-rocketchat_db_1
    image: mongo:7.0
    restart: on-failure:5
    volumes:
      - ${APP_DATA_DIR}/db:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    user: "1000:1000"

  rocketchat:
    container_name: denny-rocketchat_rocketchat_1
    image: rocketchat/rocket.chat:latest
    restart: on-failure:5
    environment:
      MONGO_URL: mongodb://mongo:27017/rocketchat
      ROOT_URL: http://umbrel-2.local:3459
      PORT: 3000
    volumes:
      - ${APP_DATA_DIR}/data:/app/uploads
    depends_on:
      - mongo
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
