version: "3.9"

services:
  app_proxy:
    environment:
      APP_HOST: denny-rocketchat_rocketchat_1
      APP_PORT: 3000

  db:
    image: docker.io/bitnami/mongodb:7.0.5-debian-11-r22
    hostname: rocketchat-db
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 20s
    environment:
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_NAME: rs0
      ALLOW_EMPTY_PASSWORD: 1
      MONGODB_SYSTEM_LOG_VERBOSITY: 3
    volumes:
      - ${APP_DATA_DIR}/db:/bitnami/mongodb
    restart: on-failure

  rocketchat:
    image: rocketchat/rocket.chat:latest
    hostname: rocketchat
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 3000 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    environment:
      MONGO_URL: mongodb://rocketchat-db:27017/rocketchat?replicaSet=rs0
      MONGO_OPLOG_URL: mongodb://rocketchat-db:27017/local?replicaSet=rs0
      ROOT_URL: http://umbrel-2.local:3458
      URL: http://umbrel-2.local:3458
      PORT: 3000
      DEPLOY_METHOD: docker
    volumes:
      - ${APP_DATA_DIR}/data:/app/uploads
    restart: on-failure
    depends_on:
      db:
        condition: service_started
