version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: trip_app_1
      APP_PORT: 8000

  app:
    image: ghcr.io/itskovacs/trip:1.3.0@sha256:4efdc91258e8700d3d307bef3025e22674150fe92e288081f600a25164e21d13
    volumes:
      - ${APP_DATA_DIR}/storage:/app/storage
    command: ["fastapi", "run", "/app/trip/main.py", "--host", "0.0.0.0"]
