version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denny-sosse_web_1
      APP_PORT: 80

  web:
    image: biolds/sosse:1.13.4@sha256:8d3bb3cfaf56fe9b93b1e3ce30d0f4b1e86f98b92054059f4e5ff121f1601a59
    restart: on-failure
    depends_on:
      - postgres
    environment:
      SOSSE_DB_NAME: sosse_db
      SOSSE_DB_USER: sosse_user
      SOSSE_DB_PASS: sosse_password
      SOSSE_DB_HOST: postgres
    volumes:
      - ${APP_DATA_DIR}/data/sosse_data:/var/lib/sosse

  postgres:
    image: postgres:17.5@sha256:3962158596daaef3682838cc8eb0e719ad1ce520f88e34596ce8d5de1b6330a1
    restart: on-failure
    environment:
      POSTGRES_USER: sosse_user
      POSTGRES_PASSWORD: sosse_password
      POSTGRES_DB: sosse_db
    volumes:
      - ${APP_DATA_DIR}/data/postgres_data:/var/lib/postgresql/data
