version: "3.7"

services:

  app_proxy:
    environment:
      APP_HOST: denny-akaunting_app_1
      APP_PORT: 80

  app:
    image: docker.io/akaunting/akaunting:latest
    restart: on-failure
    environment:
      AKAUNTING_SETUP: "true"
      APP_URL: http://umbrel-2.local:8773
      LOCALE: en-US
      DB_HOST: denny-akaunting_db_1
      DB_PORT: 3306
      DB_NAME: akaunting
      DB_USERNAME: admin
      DB_PASSWORD: akaunting_password
      DB_PREFIX: asd_
      COMPANY_NAME: "My Company"
      COMPANY_EMAIL: my@company.com
      ADMIN_EMAIL: me@company.com
      ADMIN_PASSWORD: password
    #volumes:
      # ${APP_DATA_DIR}/data:/var/www/html
    depends_on:
      - db

  db:
    image: mariadb:latest
    restart: on-failure
    environment:
      MYSQL_DATABASE: akaunting
      MYSQL_USER: admin
      MYSQL_PASSWORD: akaunting_password
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
      - ${APP_DATA_DIR}/db:/var/lib/mysql
