version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denny-lunalytics_web_1
      APP_PORT: 2308

  web:
    image: ksjaay/lunalytics:latest@sha256:df08b925ef5def35aebbb65bca20bfa9822064a7023a7ee21ea9611ba3fe81fc
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 2308 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    volumes:
      - ${APP_DATA_DIR}/data/lunalytics_data:/app/data:rw
      - ${APP_DATA_DIR}/data/logs:/app/logs:rw