version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: denny-cobalt_web_1
      APP_PORT: 9001
      PROXY_AUTH_ADD: "false"
  web:
    image: dennysubke/cobalt:11.2.3@sha256:3e864bdd11058f5c37e0f81457462956de511389c97fdb40609f7dbfd50998bd
    read_only: true
    restart: on-failure
    user: "1000:1000"
    ports:
      - 9013:9000
    environment:
      API_URL: "http://umbrel-2.local:9013/"
      API_AUTH_REQUIRED: 0
      DURATION_LIMIT: 86400
