version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: denny-cobalt_web_1
      APP_PORT: 9001
      PROXY_AUTH_ADD: "false"
  web:
    image: dennysubke/cobalt:11.2.2@sha256:f0a997d581f35154db80f7fa930941948d388db98eeb4453ba68d1a65c5372a5
    read_only: true
    restart: on-failure
    user: "1000:1000"
    ports:
      - 9013:9000
    environment:
      API_URL: "http://umbrel-2.local:9013/"
      API_AUTH_REQUIRED: 0
      DURATION_LIMIT: 86400
