version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denny-syncin_web_1
      APP_PORT: 8080

  web:
    image: syncin/server:1
    container_name: denny-syncin_web_1
    restart: always
    environment:
      SYNCIN_MYSQL_URL: "mysql://syncin:syncinpassword@mariadb:3306/sync_in"
      SYNCIN_AUTH_TOKEN_ACCESS_SECRET: "changeAccessWithStrongSecret"
      SYNCIN_AUTH_TOKEN_REFRESH_SECRET: "changeRefreshWithStrongSecret"
      SYNCIN_APPLICATIONS_FILES_DATAPATH: "/app/data"
      SYNCIN_APPLICATIONS_FILES_ONLYOFFICE_ENABLED: "false"
      SYNCIN_APPLICATIONS_FILES_ONLYOFFICE_SECRET: "onlyOfficeSecret"
      INIT_ADMIN_LOGIN: "admin"
      INIT_ADMIN_PASSWORD: "changeme"
      PUID: 1000
      PGID: 1000
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
      - ${APP_DATA_DIR}/desktop_releases:/app/static/releases  # Entferne :ro
    depends_on:
      - mariadb
    logging:
      driver: json-file
      options:
        max-size: "25m"
        max-file: "5"

  mariadb:
    image: mariadb:11
    container_name: denny-syncin_mariadb_1
    restart: always
    command: --innodb_ft_cache_size=16000000 --max-allowed-packet=1G
    environment:
      MYSQL_ROOT_PASSWORD: MySQLRootPassword
      MYSQL_DATABASE: sync_in
      MYSQL_USER: syncin
      MYSQL_PASSWORD: syncinpassword
    volumes:
      - ${APP_DATA_DIR}/mariadb:/var/lib/mysql
