server:
  trustProxy: true
mysql:
  url: mysql://syncinuser:syncinpass@db:3306/sync_in
auth:
  token:
    access:
      secret: changeAccessWithStrongSecret
    refresh:
      secret: changeRefreshWithStrongSecret
applications:
  files:
    dataPath: /app/data
    onlyoffice:
      enabled: false
      secret: onlyOfficeSecret
