version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denny-hedgedoc_web_1
      APP_PORT: 3000

  web:
    image: lscr.io/linuxserver/hedgedoc:latest
    restart: on-failure
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=hedgedoc
      - DB_PASS=hedgedocpass
      - DB_NAME=hedgedoc
      - CMD_DOMAIN=umbrel-2.local:3456
      - CMD_URL_ADDPORT=false
      - CMD_PROTOCOL_USESSL=false
      - CMD_PORT=3000
      - CMD_ALLOW_ORIGIN=*
      - CMD_DB_DIALECT=mysql
      - CMD_ALLOW_ANONYMOUS=true
      - CMD_ALLOW_ANONYMOUS_EDITS=true
      - CMD_SESSION_SECRET=XjL+Z6Jq8nBQXvFrOb1SajCcKcmqH6PWaaEbkO3HB/3iRueYs0qqEiJQ4C/TEsmE
      - UPLOADS_MODE=0755
    volumes:
      - ${APP_DATA_DIR}/config:/config
    depends_on:
      - db

  db:
    image: mariadb:10.11
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=hedgedoc
      - MYSQL_USER=hedgedoc
      - MYSQL_PASSWORD=hedgedocpass
    volumes:
      - ${APP_DATA_DIR}/db:/var/lib/mysql
