version: "3.7"

services:
  database:
    image: mariadb:11.8
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: hedgedoc
      MYSQL_USER: hedgedoc
      MYSQL_PASSWORD: hedgedocpass
    volumes:
      - ./db-data:/var/lib/mysql
    restart: unless-stopped

  hedgedoc:
    image: quay.io/hedgedoc/hedgedoc:stable
    ports:
      - "3456:3000"
    environment:
      CMD_DB_URL: mysql://hedgedoc:hedgedocpass@database:3306/hedgedoc?charset=utf8mb4
      CMD_DOMAIN: localhost:3000
      CMD_URL_ADDPORT: "false"
      CMD_PROTOCOL_USESSL: "false"
      CMD_ALLOW_ORIGIN: "*"
      CMD_ALLOW_ANONYMOUS: "true"
      CMD_ALLOW_ANONYMOUS_EDITS: "true"
      CMD_SESSION_SECRET: supersecret123
      UPLOADS_MODE: "0755"
    depends_on:
      - database
    restart: unless-stopped
