version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: denny-hedgedoc_web_1
      APP_PORT: 3000

  web:
    image: quay.io/hedgedoc/hedgedoc@sha256:25374344ce4cbf4e372fc29b5df2675ae981cad8512beda9088ecf94c6cfc5ba
    user: "1000:1000"
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/uploads:/hedgedoc/public/uploads
    environment:
      - CMD_DOMAIN=umbrel-2.local:3456
      - CMD_URL_ADDPORT=false
      - CMD_PROTOCOL_USESSL=false
      - CMD_PORT=3000
      - CMD_ALLOW_ORIGIN=*
      - CMD_DB_URL=mysql://admin:umbrel@database:3306/umbrel_hedgedoc
      - CMD_ALLOW_ANONYMOUS=false
      - CMD_ALLOW_ANONYMOUS_EDITS=false
      - CMD_SESSION_SECRET=XjL+Z6Jq8nBQXvFrOb1SajCcKcmqH6PWaaEbkO3HB/3iRueYs0qqEiJQ4C/TEsmE #${APP_SEED}
      - UPLOADS_MODE=0777
      # PUID=1000
      # PGID=1000
    depends_on:
      database:
        condition: service_started

  database:
    image: mariadb:11.8-noble-rc@sha256:ce3ce0a61f9cec258cc95f3dcebd0eaebe012712aa3d546f374159dfc799bbc8
    user: "1000:1000"
    environment:
      - TZ=Europe/Berlin
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=umbrel_hedgedoc
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=umbrel
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APP_DATA_DIR}/data/db:/var/lib/mysql:rw
    restart: on-failure
