version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: denny-hedgedoc_web_1
      APP_PORT: 3000

  web:
    image: quay.io/hedgedoc/hedgedoc@sha256:25374344ce4cbf4e372fc29b5df2675ae981cad8512beda9088ecf94c6cfc5ba
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/uploads:/hedgedoc/public/uploads
    environment:
      - CMD_DOMAIN=umbrel-2.local:3456
      - CMD_URL_ADDPORT=false
      - CMD_PROTOCOL_USESSL=false
      - CMD_PORT=3000
      - CMD_ALLOW_ORIGIN=*
      # PostgreSQL DB URL, User: admin, Passwort: umbrel, DB: umbrel_hedgedoc
      - CMD_DB_URL=postgres://admin:umbrel@database:5432/umbrel_hedgedoc
      - CMD_ALLOW_ANONYMOUS=true
      - CMD_ALLOW_ANONYMOUS_EDITS=true
      - CMD_SESSION_SECRET=XjL+Z6Jq8nBQXvFrOb1SajCcKcmqH6PWaaEbkO3HB/3iRueYs0qqEiJQ4C/TEsmE
      - UPLOADS_MODE=0755
      - PUID=1000
      - PGID=1000
    depends_on:
      database:
        condition: service_started

  database:
    image: postgres:15.4
    environment:
      - TZ=Europe/Berlin
      - POSTGRES_DB=umbrel_hedgedoc
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=umbrel
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APP_DATA_DIR}/data/db:/var/lib/postgresql/data:rw
    restart: on-failure
