version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: denny-hedgedoc_web_1
      APP_PORT: 3000

  web:
    image: quay.io/hedgedoc/hedgedoc@sha256:25374344ce4cbf4e372fc29b5df2675ae981cad8512beda9088ecf94c6cfc5ba
    user: "1000:1000"
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/uploads:/hedgedoc/public/uploads
    environment:
      - CMD_DOMAIN=umbrel-2.local:3456
      - CMD_URL_ADDPORT=false
      - CMD_PROTOCOL_USESSL=false
      - CMD_PORT=3000
      - CMD_ALLOW_ANONYMOUS=false
      - CMD_ALLOW_ANONYMOUS_EDITS=true
      - CMD_DEFAULT_PERMISSION=private
      - CMD_ALLOW_EMAIL_REGISTER=false
      - CMD_ALLOW_GRAVATAR=false
      - CMD_DB_URL=postgres://admin:umbrel@database:5432/umbrel_hedgedoc
      - NODE_ENV=production
    depends_on:
      - database

  user_setup:
    image: quay.io/hedgedoc/hedgedoc@sha256:25374344ce4cbf4e372fc29b5df2675ae981cad8512beda9088ecf94c6cfc5ba
    depends_on:
      - web
    volumes:
      - ${APP_DATA_DIR}/data/uploads:/hedgedoc/public/uploads
    entrypoint: >
      sh -c "
        echo 'Waiting for HedgeDoc to be ready...';
        sleep 10;
        node /hedgedoc/bin/manage_users --add admin@admin.com --password <<EOF
        umbrel
        umbrel
        EOF
        echo 'Admin user created.';
      "

  database:
    image: postgres:15.4
    environment:
      - TZ=Europe/Berlin
      - POSTGRES_DB=umbrel_hedgedoc
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=umbrel
    volumes:
      - ${APP_DATA_DIR}/data/db:/var/lib/postgresql/data:rw
    restart: on-failure
