version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: denny-vtigercrm_web_1
      APP_PORT: 80

  web:
    build: .
    container_name: denny-vtigercrm_web_1
    restart: unless-stopped
    environment:
      mysql_user: ${mysql_user}
      mysql_pass: ${mysql_pass}
    volumes:
      - ${APP_DATA_DIR}/data/html:/var/www/html
      - ${APP_DATA_DIR}/data/mysql:/var/lib/mysql
